# Generated by Django 5.1.6 on 2025-02-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ingredients_raw', models.TextField(help_text='Unstructured text of ingredients')),
                ('ingredients_structured', models.JSONField(blank=True, help_text='Structured ingredients data generated by LLM', null=True)),
                ('instructions', models.TextField(help_text='Step-by-step instructions for the recipe')),
                ('is_cookidoo', models.BooleanField(default=False, help_text='Is this a Cookidoo recipe?')),
                ('can_freeze', models.BooleanField(default=False, help_text='Can this meal be pre-cooked and frozen?')),
                ('number_of_people', models.PositiveIntegerField(help_text='Number of people the recipe serves')),
                ('duration_work', models.PositiveIntegerField(blank=True, help_text='Work duration in minutes', null=True)),
                ('duration_total', models.PositiveIntegerField(blank=True, help_text='Total duration in minutes from start to finish', null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='recipes/')),
            ],
        ),
    ]
